### ISSUE TITLE
Do not show a point marker, when the address is coarse

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/ServicesAdvisor-2.0#33] opened 2016-05-26 23:56 UTC
If we only have an address at the city level or something similar, we still show a map marker at a specific location (for example city center). This can be confusing, as the user may actually use that as the physical location. In such cases we shouldnt have fine markers.  Refer to #32 for details

**Comment by fmann** [comment] 2016-06-06 21:55
Clarification: currently locations must select down to the most granular (leaf) level. You cannot select a coarse location.  

Ticket #32 suggests changing that behaviour. These two should be addressed at the same time.

**Comment by PeaceGeeksProjects** [comment] 2016-06-06 22:08
This is a duplicate of portions of #32.  Closing

**Closed by PeaceGeeksProjects** 2016-06-06 22:08 UTC
Labels: backend, front end, needsdesign
