### ISSUE TITLE
Detailed information on the right not displaying

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#5] opened 2016-03-09 01:40 UTC

**Comment by fmann** [comment] 2016-03-09 21:46
Not displaying in the Service Advisor?  Not displaying on the node display?  Not displaying in the edit form?  Please clarify.

**Comment by PeaceGeeks** [comment] 2016-03-09 22:02
Yes not displaying on the map right side panel - you guys may have fixed this last week - Mack seemed to be aware of this when I discussed it with him. if the activity/ node details are displaying on the right on the public facing view, then we are good.

**Comment by fmann** [comment] 2016-03-09 22:36
When we switched from the location selection by clicking on a map to location selection by picking a location in a taxonomy of hierarchical location data, the map on the location nodes in http://admin.jordan.servicesadvisor.org/ went away.  Adding a map there that used the location information off the location taxonomy term is certainly possible but ... non-trivial.

**Comment by PeaceGeeks** [comment] 2016-03-09 22:58
So that means that none of the nodes map at this time?

**Comment by fmann** [comment] 2016-03-09 23:03
Just talked to Renee. This was related to breakage in the SA Client code caused by sector not being selected. This was fixed between day one and day two of the demo, so I am closing this.

**Closed by fmann** 2016-03-09 23:03 UTC
